[tool.poetry]
name = "la-ucu"
version = "0.1.0"
description = "Packages for LinearAlgebra-UCU"
authors = ["Ivan Havlytskyi", "Oleksandr Kharytonov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.11"
torch = "^2.1.0"
torchvision = "^0.16.0"
numpy = "^1.26.0"
scipy = "^1.11.0"
scikit-learn = "^1.3.0"
matplotlib = "^3.8.0"
ipykernel = "^7.0.1"
pandas = "^2.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"